version: '3.9'

services:
  db:
    image: 'postgres:latest'
    restart: 'always'
    container_name: 'java_postgres'
    shm_size: '128mb'

    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=java'

