spring:
  application:
    name: CatalogService
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java
    username: sa
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        open-in-view: false
        ddl-auto: update
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
       include: metrics, prometheus, health
  endpoint:
    health:
      show-details: always



